name: Data Benchmarking Tests

on: [ push, workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  dl_data:
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.cache_key.outputs.cache_key }}

    steps:
      - name: Set date var
        id: cache_key
        run: echo "cache_key=web-data-$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

      - name: Cache Data
        id: cache-data
        uses: actions/cache@v3
        with:
          path: data
          key: ${{ steps.cache_key.outputs.cache_key }}

      - name: Make data dir
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: mkdir data -p -v

      - name: Fetch Data File Crime_Data_from_2020_to_Present.csv
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: curl https://data.lacity.org/api/views/2nrs-mtv8/rows.csv?accessType=DOWNLOAD -o data/Crime_Data_from_2020_to_Present.csv

      - name: Fetch Data File reddit_account_data.csv.gz
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: curl https://files.pushshift.io/reddit/69M_reddit_accounts.csv.gz -o data/reddit_account_data.csv.gz

      - name: Unzip reddit_account_data.csv.gz
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: gzip -d data/reddit_account_data.csv.gz

      - run: ls -laR /

  build:
    runs-on: ubuntu-latest
    needs: [ "dl_data" ]

    strategy:
      matrix:
        python-version: [ "pypy3.8", "3.8", "pypy3.9", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: data
          fail-on-cache-miss: true
          key: ${{ needs.dl_data.outputs.cache_key }}

      - name: Check cache hit
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - run: ls -laR /

      - name: Update pip & setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: pip install .

      - name: Run tests
        run: python -m data_processing

      # https://github.com/actions/setup-python/issues/350
      - name: Run tests
        run: pytest --benchmark-autosave --benchmark-save-data --benchmark-cprofile=tottime
        # https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f
        if: success() || failure()

      - name: Archive performance coverage results
        uses: actions/upload-artifact@v3
        with:
          name: perf-benchmarks
          path: .benchmarks/*
